### ISSUE TITLE
npm ERR! code ECONNRESET issue

### ISSUE THREAD

**Issue by real-new-programmer** [npm/registry-issue-archive#112]
I'm running "npm install" from Amazon EC2 in eu-west-1, and I'm seeing many random "npm ERR! code ECONNRESET 151.101.60.162:443" starting from around 12 pm 01/03/2017 PST

I'm running with:
 node v4.3.2
 npm v2.14.12

**Comment by soldair** [comment]
hey sorry for taking so long to get back with you.
i believe the version of node you are using may have a keep alive pool bug
https://github.com/nodejs/node/issues/3595

which was related to your problem here
https://github.com/npm/registry/issues/10#issuecomment-217141066

so please use a node version >=4.4 >=5.4 and >= 6 and let me know if that solves things. =)
