### ISSUE TITLE
Webhook limits

### ISSUE THREAD

**Issue by jschr** [npm/registry-issue-archive#115]
Are there any plans to increase the webhook limit from 100? 

I'm building a service to deploy client-side applications and thought it would be a pretty awesome workflow to connect directly to npm instead of building my own simpler package manager. I would be creating a webhook on behalf of my users such that when a new version of the users app is published, I can trigger redeploys from my service. The 100 webhook limitation would unfortunately not work for my use case though.

**Comment by soldair** [comment]
not at this time but ill bring it up. 
3 thoughts though.

- folks that use your service could point webhooks for their package or organization to your webhook deploy endpoint and that wouldn't cause a problem with limits because each of them would have 100 to use and a scope or author hooks matches many packages.

- you can't add a webhook for a private module that you dont have access to so to use the proposed method customers would have to `npm owner add` your deploy account to their packages or a team in their org if they want to deploy private code. both problems are handled by the first thought.

- the interface we provide for handling lots of changes from lots of people is the changes feed. you may want to follow the changes feed directly https://github.com/npm/concurrent-couch-follower pointed to https://replicate.npmjs.com . the downside again is that you wont get private changes at this time.

it seems to me that you will need to run a hook-recieiver and have folks `wombat hook add` a hook for their deployable app to your service. you will also need to store the secret on your side and set it on the hook so you can verify that the events come from real changes

anyway hope this helps.

**Comment by jschr** [comment]
@soldair thanks for the insight.

Having users setup the webhook sounds like a better approach but would be preferable that they don't need to need a paid npm account and to have a more convenient way to set it up rather than requiring another tool. Something like github's Webhook UI or defining it in package.json would be cool! 

Appreciate the consideration.
