### ISSUE TITLE
publish SHA3 hashes and file sizes of packages 

### ISSUE THREAD

**Issue by graingert** [npm/registry-issue-archive#137]
It may be possible for someone to create a colliding version of a popular package and tools like Yarn (see https://github.com/yarnpkg/yarn/issues/816) would not be able to detect it.

This would be made impossible by publishing the SHA3 hash or file size of the tar.gz

**Comment by zkat** [comment]
@graingert I don't consider it appropriate to switch to SHA3 until such a time as node itself supports it natively. Which will hopefully be soon, as I'm sure plenty of folks are [making big sad puppy eyes at OpenSSL](https://github.com/openssl/openssl/issues/439) to just get an implementation going for it (which is where node would get its impl from). This SHA3 implementation would still take a while to propagate, but it would be the one I trust enough to use, tbh.

THAT SAID

We are already working on switching to more secure algorithms and paving the way for us to be able to smoothly and incrementally upgrade to sha3 as it becomes available! We are already rolling out `sha512` using the [subresource integrity](https://npm.im/ssri) format, which will let us use the same field for publishing sha3 while still allowing for backwards compatibility. I've [made a comment in Yarn's tracker](https://github.com/yarnpkg/yarn/issues/816#issuecomment-301217417) about how to use the implementation, and how to maximize forwards-compatibility.

The other part of your question, file size, is not something that needs any further action: we send a `Content-Length` along with our tarballs which you can use to verify file size. If your intention is to use tarball size to protect against SHAttered, though, you might want to know that not only do the two generated PDFs have the same sha1sum, they have _the exact same size_. You literally can't distinguish without detecting their content.

The good news here is that by the time sha1 attacks become practical enough, we'll have long moved off sha1 itself.

I'm gonna close this issue since we're either already doing this, or it's unnecessary for us to take any further action. Happy hacking~
