### ISSUE TITLE
Publish to npm enterprise got incorrect user

### ISSUE THREAD

**Issue by wesleytodd** [npm/registry-issue-archive#16]
I have the user `wes` on our npm enterprise and published a new package today on our internal namespace.  When the publish was successful I took a look at its page in the onsite install and it was published by `andrew`.  As far as I can tell that is just the last person to create an account via `npm adduser --registry="our.onsite.com:8080" --scope="@ournamepsace"`.

Let me know if there is any more information I can provide to help debug.

**Comment by nexdrew** [comment]
@wesleytodd I assume you're using the "Open" auth model in your npm Enterprise settings?  If so, this is a known limitation of that auth model which we have a fix for and will be releasing very soon.

**Comment by wesleytodd** [comment]
Ahh, yes we are, thanks for the quick response.  Feel free to re-open this if you don't have another place where this has been documented as a bug that I didn't find.

**Comment by nexdrew** [comment]
@wesleytodd We don't really have a public place where the bug was documented, so this issue works fine, thanks for reporting!

I can point you here https://github.com/npm/npme-docker/pull/71, but that PR just references another PR (with the description and fix) on a private repo.

It's not technically a bug since it was expected behavior, it's just that the functionality was less than ideal. :)

Basically the "Open" auth model was using the same static token for everyone that authenticates with the registry (via `npm adduser`) or with the website (via login form), and the user info associated with that token would be overwritten each time, so there would really only be a single user at any given point, and the last login wins.

We have changed this so that it generates a new unique token for each login and preserves the associated user info for each token, thereby mimicking the way other auth models work.

That being said, please keep in mind that the "Open" auth model is just meant for testing things out and should not be used in a production instance. One of the nice things about npm Enterprise is you can plug it into your existing internal auth provider, so you don't have to import your whole userbase into another system just to use your private registry and website.

Anyway, let us know if you run into any more issues or questions. You can either open issues here, send an email to support@npmjs.com, or open issues against [the npme installer repo](https://github.com/npm/npme-installer/issues). Thanks!

**Comment by nexdrew** [comment]
@wesleytodd Note that the fix has been released as npm Enterprise version `9824cc1 (288)`.

Please upgrade via admin console on port 8800 at your earliest convenience (and update the `npme` bin on your host via `sudo npm i -g npme --ignore-scripts`) . Thanks!

**Comment by wesleytodd** [comment]
@nexdrew Awesome! Thanks for the quick response and solution.  My apps always have "features" like this, lol, so I know how it is.  I will get ours updated and confirm the fix here when I do.

**Comment by wesleytodd** [comment]
Hey, I may have gotten confused, the package we have installed is `npmo` not `npme`.  I am assuming there is a real difference.  Basically the script our Ops guy ran on that server was the one provided in the instructions when we signed up, and it installed `npmo` for us.  Should we be updating that package? did the fix make it into `npmo` as well?  Clearly I don't know how this all works so sorry for my noob questions.

**Comment by nexdrew** [comment]
@wesleytodd Hey, that's not your fault at all - we recently rebranded npm On-Site (which was installed via the `npmo` bin) to npm Enterprise (installed via the `npme` bin), but they're actually the same product! The bins are the same too, except that the `npmo` bin will no longer be updated.

You can safely remove the `npmo` bin via `sudo npm uninstall -g npmo` and replace it with the `npme` bin via `sudo npm i -g npme --ignore-scripts`. This will not affect your npm Enterprise appliance/registry/website.

The fix for the Open auth model is distributed via the appliance update that is run from the admin console and actually has nothing to do with the `npme` bin, but we will be adding features to the product that will be more easily leveraged if you grab the latest `npme` bin and keep it somewhat up-to-date. (When run, the bin will check for its own updates via `update-notifier`, so it should help notify you when its own updates are available.) We use the bin to allow sysadmins to run infrequent, but sometimes important, commands against the Docker images that are distributed via the admin UI on port 8800.

Clear as mud?

**Comment by raybooysen** [comment]
Just to confirm to use npme we need to manually uninstall npmo and then
install npme?

Is it mandatory to do that if we upgrade to the latest in the admin console?

Regards
Ray

**Comment by nexdrew** [comment]
@raybooysen No, you can install `npme` without uninstalling `npmo`. I just think doing so will help avoid confusion later on.

No, it's not mandatory, just recommended. :) We will probably be adding commands to `npme` that will make it easier to enable certain features in the appliance, that's all.

Sorry for the confusion! We're trying to put things in place now so that you won't have to do this again in the future. Thanks for your patience and understanding.

**Comment by wesleytodd** [comment]
Question: with the above commands we will not be destroying the running docker container on uninstall?  And the `--ignore-scripts` flag will skip setting up docker container for the new `npme` package?  Just wanted to confirm all this because we don't want to accidentally remove our running instance.

**Comment by nexdrew** [comment]
@wesleytodd That is correct, uninstalling the `npmo` bin will not affect your running instance, and using `--ignore-scripts` when installing `npme` will skip the Replicated install/update and will also not affect your running containers.
