### ISSUE TITLE
Need info on scaling on number of users in NPMe

### ISSUE THREAD

**Issue by kiranshashiny** [npm/registry-issue-archive#182]
Is it possible to add a section on how many users can be accommodated with the hardware listed.

and also some scaling information would help in this link

https://npme.npmjs.com/docs/up-and-running/requirements.html
e.g: The requirements would suit for 3000 users.
Likewise what is the new hardware needed if we were to have double the number of users.

Second Issue :
Please add suggested requirements for Load Balancer and Nginx as well.

Currently we are trying to set up a front end server and do NOT see any documented references - so this addition would help.

**Comment by ashleygwilliams** [comment]
hi! thanks for filing this issue. i've assigned our npme expert @arobson this question, hopefully he can help ya out!

**Comment by arobson** [comment]
@kiranshashiny hi Shashi, I'll work with the npmE team to update our documents and make some recommendations where we can.

Since user count doesn't accurately predict utilization patterns and because we don't have access to analytics from our customers' installations, we can only provide ball park estimates at best. Every customer's use case is going to vary significantly depending on their work load, network, VM configuration, etc. The best thing you can do is monitor your machines and add capacity as needed to ensure there's little or no disruption during peak times.

As for hardware requirements for an NGiNX VM serving as the load balancer, again, it's going to depend on the utilization and work load, but I wouldn't go any smaller than 2 Cores and 4 GB of RAM. If you're curious what I'm basing this on, you can check out the NGiNX sizing guide that has a lot of performance data included:

https://cdn-1.wp.nginx.com/wp-content/files/nginx-pdfs/Sizing-Guide-for-Deploying-NGINX-on-Bare-Metal-Servers.pdf

This explains how they tested:
https://www.nginx.com/blog/nginx-plus-sizing-guide-how-we-tested/

Please keep in mind that these metrics are for bare metal servers and *not* virtual machines so you shouldn't expect to get the same kinds of results (hence my recommendation that 2 CPU/4 GB RAM is the minimum you ought to consider). Also keep in mind that the workload you're looking at for npmE is larger file transfers so the workload is atypical compared to the baseline used in the example. Adding Varnish to the the LB VM for cache will relieve pressure from your npmE servers but require more resources on the LB.

If you have additional questions about npmE, please send them to `support@npmjs.com`.
