### ISSUE TITLE
Package readme not being rendered

### ISSUE THREAD

**Issue by olivernn** [npm/registry-issue-archive#207]
My [package](https://www.npmjs.com/package/lunr) displays without a readme, though there definitely is one in the [repository](https://github.com/olivernn/lunr.js/blob/master/README.mdown) (and as part of the [package](https://unpkg.com/lunr@2.1.3/README.mdown)).

I'm pretty sure it _used_ to display, though I can't remember how long ago that was. I haven't changed the location or filename of the readme in the repository in forever.

**Comment by ashleygwilliams** [comment]
hi @olivernn sorry you are dealing with this!

i believe that you are running into this issue because we changed how our package pages render readmes ~6mos ago and i believe we may have skipped the `.mdown` extension! we are def going to look into that on our end, but if you publish a new patch version and change the `.mdown` extension on your README to `.md` you should be all set!

please feel free to reopen the issue if you still see problems!

**Comment by ashleygwilliams** [comment]
also- @olivernn turns out this fix was super easy so i actually have a PR for it in now, if you star and unstar your package in a few hours you should be good to go!

**Comment by olivernn** [comment]
@ashleygwilliams cool, thanks for taking a look at this, I'll try it out tomorrow and let you know.

**Comment by olivernn** [comment]
@ashleygwilliams I tried toggling the star (multiple times, with some page reloads in between) without any luck, was you change merged yet?

No big deal, I'll change the file extension for the next release.
