### ISSUE TITLE
Unable to publish scoped module, despite public access

### ISSUE THREAD

**Issue by andreypopp** [npm/registry-issue-archive#23]
See npm/npm#12633.

---

```
mb % npm whoami
prometheusresearch
mb % npm publish --access public
npm ERR! publish Failed PUT 402
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/andreypopp/.nvm/versions/node/v5.1.0/bin/node" "/Users/andreypopp/.nvm/versions/node/v5.1.0/bin/npm" "publish" "--access" "public"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E402

npm ERR! You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @prometheusresearch/react-ui
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andreypopp/Workspace/prometheusresearch/react-ui/npm-debug.log
```

**Comment by ashleygwilliams** [comment]
you might need to use `--access=public`

**Comment by othiym23** [comment]
`nopt` isn't particular about the presence of the '=', so this is probably something else.

**Comment by chrisdickinson** [comment]
Hi! If you run `npm access public @prometheusresearch/react-ui` you should be able to publish afterwards.

This is a symptom of a (recently fixed!) issue with the registry:
1. `npm publish`'ing a scoped module defaults to private access,
2. Our authentication machinery would create and store metadata for the package, including a `private: true` flag.
3. Subsequent checks with the authentication machinery would _also_ check for the presence of a valid license, and would return 402 in its absence.
4. This would surface as someone accidentally running `npm publish` inside of a new scoped module (with no `--access=public` flag) and then being unable to install or publish that module.

The workaround for such packages is to use `npm access public <packagename>` which does not run the license check. A check has been added to prevent new private packages from being published if the publisher doesn't have a valid license, in order to keep this happening in the future. Sorry for the trouble! If you continue to have problems please let me know and I'd be happy to work through them with you. Thanks!

**Comment by andreypopp** [comment]
@chrisdickinson yes, that worked, thanks.

Still wondering why changing name from `react-ui` to `react-ui-component` helped initially.
