### ISSUE TITLE
404s for coffeescript-1.12.8

### ISSUE THREAD

**Issue by bryevdv** [npm/registry-issue-archive#248]
Seeing this all day on `npm install`, [causing CI builds to fail](https://travis-ci.org/bokeh/bokeh/jobs/311654703)

> npm ERR! fetch failed https://registry.npmjs.org/coffeescript/-/coffeescript-1.12.8.tgz

However `npm show coffeescript versions` clearly includes `1.12.8` in the list of published versions.

**Comment by soldair** [comment]
hey! thanks for letting us know ill take a look

**Comment by bryevdv** [comment]
Thanks, this is blocking a hotfix release of Bokeh, please let me know if theres anything I can assist with.

**Comment by soldair** [comment]
This tarball is never going to exist sadly as it was unpublished. Probably published in error. I believe you'll need to switch to version 1.12.7

Now that the document properly reflects available versions an `npm install coffeescript@1.12.7` should fix it right up. If you have a package-lock.json you may have to remove it to update to the available version.

**Comment by soldair** [comment]
Sorry i left my first response to you unsent in the text area last night. 

It looks like due to some backend serving changes i sent a stale version of the package metadata to you which referenced an unpublished version of coffeescript. 1.12.8 

this stale document has been fixed and 1.12.7 should auto install if you use a compatible semver range.

**Comment by bryevdv** [comment]
Yes it seems to be working again now, thanks for looking into it
