### ISSUE TITLE
Cannot install scoped packages.

### ISSUE THREAD

**Issue by NicolasPelletier** [npm/registry-issue-archive#272]
The following command fails when you have `_auth` defined in your package.json
```
$ npm i -D @storybook/addons --verbose
```

As more and more package are starting to be scoped, it it important that we can use `_auth` for internal npm repository and still be able to get packages in the publish repository anonymously.

The issue is being discussed here: https://github.com/npm/npm/issues/19254. The discussion seems to lead toward a registry problem and not an npm client problem so I though I would open the issue here.

My setup is:
```
$ npm -v && node -v
5.6.0
v8.9.4
```

My npmrc content is:
```
_auth = <somekey>
always-auth = false
email = myemail@myfirm.com
prefix=/Users/pelletn/.npm-prefix
@myfirm:registry=<an internal registry url>
```

The debug log is here ( [2018-01-22T13_57_42_780Z-debug.log](https://github.com/npm/registry/files/1652209/2018-01-22T13_57_42_780Z-debug.log) ), but the jist of it is:
```
npm http fetch GET 404 https://registry.npmjs.org/@storybook%2faddons 876ms
npm verb stack Error: 404 Not Found: @storybook/addons@latest
npm verb stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
```

It is odd that I get a 404. If the authentication was buggy, I would expect to get a 401 or something like that.

If I comment our the `_auth` property in my `.npmrc`, I get this:
```
npm http fetch GET 200 https://registry.npmjs.org/@storybook%2faddons 510ms
npm verb correctMkdir /Users/pelletn/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/pelletn/.npm/_locks/staging-6b4f4752cb43616f.lock for /private/tmp/20180122/node_modules/.staging
http fetch GET 200 https://registry.npmjs.org/@storybook/addons/-/addons-3.3.10.tgz 622mscks/staging-6b4f4752cb43616f.lock for /private/tmp/20180122/node_modules/.staging
```

**Comment by soldair** [comment]
the _auth key in npmrc is deprecated. i dont even recall the last version of the npm client that created it. it probably should still work but its clear you're running into issues and we'll investigate. you get a 404 because these credentials are  being denied but you should get the package anyway because its public.

but to fix your situation lets update your login. or leave _auth deleted.
please run npm login and follow the prompts this will create a 
`//registry.npmjs.org?authToken=xxxxxxxx `
line in yoiur .npmrc

now for internal/third party registries we strongly suggest you use a scope. this is because you can set login credentials per scope in npm rc and npm will do the work of finding out where to fetch what scopes packages.

npm login --scope @mypersonalscope --registry https://mylocalnpmregistry

this would cause the cli to fetch everything for @mypersonalscope from https://mylocalregistry but if you want to fetch @storybook it would go to the main registry.

if you're just using the local copy as a read only mirror well you can swich registry= configs in npmrc any time you want i guess =)

**Comment by NicolasPelletier** [comment]
At the firm, we are using Artifactory by JFrog as our NPM repository. The recommended way of populating our `.npmrc` is to use and _auth parameter. This is why I have done it that way.

If I used the `npm login` command you recommend above, I get a the following error:
```
$ npm login --scope @myfirmscope --registry https://<our Artifactory Instance>/artifactory/api/npm/myfirm-npm
Username: (pelletn)
Password: (<default hidden>)
Email: (this IS public) (myemail@myfirm)
npm ERR! code E404
npm ERR! 404 Registry returned 404 for PUT on undefined
npm ERR! 404
npm ERR! 404  'org.couchdb.user:pelletn' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pelletn/.npm/_logs/2018-01-26T20_07_47_447Z-debug.log
```
Clearly, Artifactory does not support this request.

I never had problem using my npmrc with the `_auth` entry until I tried to get scoped packages from the internet. I can get any other packages, as long as their name is not scoped.

**Comment by NicolasPelletier** [comment]
This is not an issue for me anymore. I expect the back end of npm was modified to accept the _auth header or something like that without errors.
