### ISSUE TITLE
Getting `InternalError` for published package

### ISSUE THREAD

**Issue by SimenB** [npm/registry-issue-archive#54]
https://registry.npmjs.org/csslint-stylish/-/csslint-stylish-0.0.5.tgz

Returns:

``` js
{
  code: "InternalError",
  message: "Cannot read property '0.0.5' of undefined"
}
```

**Comment by soldair** [comment]
thanks for reporting. ill take a look at this

**Comment by soldair** [comment]
@SimenB it looks like the publish failed to replicate the tarball. this is very unusual and ill make sure we are traking this internally. i believe it should have reported failure on publish rather than updating the document with the new version.

what i will do is remove the failed 0.0.5 version so you can republish

**Comment by SimenB** [comment]
Great, thanks

**Comment by soldair** [comment]
@SimenB 0.0.5 has been removed. please republish at your convenience =)

**Comment by SimenB** [comment]
Published now, seems to work fine. Thanks!
