### ISSUE TITLE
Registry API? 

### ISSUE THREAD

**Issue by kevinSuttle** [npm/registry-issue-archive#6]
Something like Tonic. Are there docs for accessing a given registry programmatically (presumably read-only)?

**Comment by chrisdickinson** [comment]
Not at present, but we will be working to document the existing registry API endpoints in this repository.

**Comment by kevinSuttle** [comment]
Thanks!

**Comment by jucrouzet** [comment]
You can consult the registry via the CouchDB endpoint like any normal CouchDB database : 

https://registry.npmjs.org/less
https://registry.npmjs.org/-/_view/byKeyword?startkey=[%22lodash%22]&endkey=[%22lodash%22,{}]&group_level=3

**Comment by soldair** [comment]
The registry is not actually a couchdb even though some routes may hit one via internal proxy. This means we can't claim to support couch's features and web api.  

We are planning on having an officially supported api with docs and everything though so feel free to post  idea/feature request issues with things you would like to see.

**Comment by fengmk2** [comment]
Long ago I try to find out `the registry api` https://github.com/cnpm/cnpmjs.org/blob/master/docs/registry-api.md

Happy to see the real registry api document come out!

**Comment by ashleygwilliams** [comment]
hi all! i will be working on creating registry documentation to this repository. you'll notice that i just created a `/doc` directory :smile:

since this is in the plans, i'm going to close this issue in favor of more specific issues related to registry docs, once those docs start shipping. thanks ya'll!

**Comment by kevinSuttle** [comment]
Woot!

**Comment by ghost** [comment]
@ashleygwilliams, I noticed `http://registry.npmjs.com/-/search` does not return `404`, and instead, it returns `{}`. Which means it is possible you have a plan to provide it right?

And @fengmk2 did provide the API documents, but nothing about search.

**Comment by soldair** [comment]
it does provide a 404 statuscode but im not sure if this helps answer your question. in any case this is a closed issue and should probably not be used for further discussion

```
curl -v http://registry.npmjs.com/-/search
*   Trying 151.101.20.162...
* Connected to registry.npmjs.com (151.101.20.162) port 80 (#0)
> GET /-/search HTTP/1.1
> Host: registry.npmjs.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json
```

**Comment by ghost** [comment]
@soldair Sorry, it is my mistake.

So we have to use `/-/all` to search for now, correct?

[CNPM](https://github.com/cnpm/cnpmjs) from @fengmk2 provides two very good APIs:
- `/-/all/since`, to get packages after a specific time point.
- `/-/short`, provides only the name list.

A `xz -9e` archive of `/-/all` takes 22MBytes, 200MBytes for uncompressed, so maybe it is not a good idea to use `/-/all` for search.

Well, maybe you have good reasons not allowing search from registry, but I hope there is one API.

**Comment by soldair** [comment]
you can also use the _changes endpoint its much better because it supports streaming and since

**Comment by ghost** [comment]
Thanks for your responding. 

Result from `https://replicate.npmjs.com/_changes` returns something like this:

```
{"seq":2,"id":"_design/scratch","changes":[{"rev":"1-4136ab2028eaa41eeb63e22b028172a0"}]},
{"seq":3,"id":"_design/app","changes":[{"rev":"1-4136ab2028eaa41eeb63e22b028172a0"}]},
{"seq":4,"id":"Reston","changes":[{"rev":"1-de734a2e9145f8c74a2de62a385f49b5"}]},
{"seq":5,"id":"asyncevents","changes":[{"rev":"1-15c03acf9851eb582f77c192a4df9fe3"}]}
```

Seems not helping for a client search. Anyway, I just checked the code from npm/npmjs. It seems the only interface for search used is `/-/all`.

Thank you very much.

**Comment by soldair** [comment]
@kcauchy here are the docs for couchdb changes streams.  http://docs.couchdb.org/en/2.0.0/api/database/changes.html

here is a really great module you should use to process those changes. https://www.npmjs.com/package/changes-stream

all is a rather bad pratice because like you mentioned you have to download soo much you dont need every time.

if you want to try it follow https://replicate.npmjs.com/registry

**Comment by ghost** [comment]
Thanks for your update for changes-stream. I know nothing about couchdb.

NPM has a new implementation of search, in PR https://github.com/npm/npm/pull/13746. The old one, doesn't work any more. I tested it on different servers, none of them can perform a search. 

I will read the new implementation. Thank you very much.
