### ISSUE TITLE
Published package gives 404

### ISSUE THREAD

**Issue by jtreanor** [npm/registry-issue-archive#63]
I am a maintainer of https://www.npmjs.com/package/cordova-plugin-intercom.

We recently published version 3.0.12. However, when installing this version it gives a 404 not found error:

```
> npm install -g cordova-plugin-intercom@3.0.12
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-intercom/-/cordova-plugin-intercom-3.0.12.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
...
```

Is this a known issue? Let me know if I should be reporting this somewhere else.

**Comment by soldair** [comment]
this is exactly the correct place to report this issue.
we have had one other report this last week of a publish that seemed successful but the tarball was not successfully saved.

ill check into your module now. if it is like the other there was an error publishing the document and instead of it bubbling up the new version of the metadata was saved anyway. this should never happen.

the quickest fix for your users is to publish a new patch version asap or to point the latest dist-tag to the previous version. once we gather information i may be able to remove the failed version from your metadata because the publish was never successful.

**Comment by jtreanor** [comment]
Thanks for the quick response @soldair.
I'm in the process of releasing a patch version. Let me know if I can give you any more info.

**Comment by soldair** [comment]
I've confirmed that the temporary file never made it to it's intended location and ill be looking through our logs to see if i can get to the bottom of it to prevent this class of error in the future.

**Comment by soldair** [comment]
we unpublished version 3.0.12. you wont be able to publish over this version number again but at it wont appear in the versions portion of the metadata
