### ISSUE TITLE
Blob store having troubles?

### ISSUE THREAD

**Issue by djMax** [npm/registry-issue-archive#67]
Just published a package (private package), showing up in npm info but the tarball is 404-ing.

**Comment by soldair** [comment]
we have had some reports of false positives on publish. where storing the file fails but the json is saved anyway. The only work around at this time is to push a patch release and publish again if it's within the 24 hours you can unpublish the old version otherwise we can take care of it in support.

i hope to have an extra check deployed today to protect against this class of error but it needs more testing.

If you like please email support@npmjs.com with your module name so i can look into it.

**Comment by djMax** [comment]
thanks, that worked
