### ISSUE TITLE
registry error parsing json

### ISSUE THREAD

**Issue by kgryte** [npm/registry-issue-archive#83]
I was directed here to report a possible registry issue. See

* npm/npm#14612
* npm/npm#14619
* npm/npm#14618
* npm/npm#14576

In short, `npm` is reporting a registry error on AppVeyor and Travis CI, as well as on other platforms. The error occurs randomly. In my case, some jobs are fine and others fail causing builds to fail.

Does not appear to be a proxy/VPN issue; otherwise, CI jobs should be failing consistently (all VMs configured the same).

**Comment by soldair** [comment]
thanks for reporting this and linking these issues ill look at this now

**Comment by kgryte** [comment]
@soldair Thanks!

**Comment by soldair** [comment]
for folks experiencing 400 status code responses. (14618)

I reconfigured our cdn to retry requests internally that get a 400 response code. this should reduce the failures to only actual bad requests. i've been tailing at the logs and havn't seen a 400 request since but ill continue monitoring.

for folks experiencing error parsing json for GZIP responses that should not be gzipped. (14612)

some items went into cache without a proper `vary: accept-encoding` header for a time this weekend. Im working on something to clear these out as requests come in and ill update this issue again when it's resolved.

14619 seems to be their own proxy issue because we do not have anything in our stack that can generate that response

**Comment by kgryte** [comment]
@soldair Thanks for looking into this! Will report back if I encounter any more issues. Thanks again!
