### ISSUE TITLE
Webhooks are not posting the correct events

### ISSUE THREAD

**Issue by czardoz** [npm/registry-issue-archive#84]
I have set up a couple of webhooks. Whenever a package is published, I get a webhook for a `package:change` instead of `package:publish`. 

For example I just published a new version of https://www.npmjs.com/package/postman-collection, but I did not get a webhook call for a `package:publish` (I did get one with `package:change` though).

As a side note, as of right now, the [web UI](https://www.npmjs.com/package/postman-collection) still shows the older version of my package, but I guess that's a separate issue?

**Comment by soldair** [comment]
hey. happy to check into the change.publish issue.

Was this the first hook ever triggered for this particular package? I expect that all further publishes will be tagged with the correct event.  

This is a long standing behavior because we need at least one old version of the document to compare against to be able to determine the correct event type. if we dont have that information all we know is that it "changed"

its at the top of the list as far as bugs in hooks goes and im sorry for the inconvenience. you can run `npm star` on a package that has hooks to test and force trigger that first event.

the web ui is distinct. it should update itself but ill check that the event didn't get lost in the pipes somewhere.

**Comment by soldair** [comment]
i have reprocessed postman-collection. it should be available on the site soon.

**Comment by czardoz** [comment]
Oh I see, it was indeed the first time the webhook ran. Thanks!
